### ISSUE TITLE
Add support for buying sol pairs

### ISSUE THREAD

**Issue by fdundjer** [fdundjer/solana-sniper-bot#10]
Script supports buying usdc token pairs.
Add ability to trade sol pairs

**Comment by fdundjer** [comment]
@dtmrc Awsome, do you want to create PR to this repo with your changes?

**Comment by mrubino22** [comment]
@fdundjer you did a wonderful job, both in logic and implementation. I'm trying to swtich him on buying solana, but after several days I'm going crazy. From my wallet I can get the quantities of sol tokens (getBalance) but not the same info you get from the usdc coin. I read that you succeeded, I saw that they asked you to share the code…. if you don't want to share it, please give me some indication on what to change or implement in the code. thank you very much

**Comment by fdundjer** [comment]
@mrubino22 I've added support for sol pairs.
