### ISSUE TITLE
empty Token Accounts?

### ISSUE THREAD

**Issue by napzter13** [fdundjer/solana-sniper-bot#16]
Hi,

Trying to understands this project by running it.

Am i the only one who gets empty Token Accounts?

![image](https://github.com/fdundjer/solana-sniper-bot/assets/25500827/46470998-2b4f-4872-8362-abba66c64c59)

![image](https://github.com/fdundjer/solana-sniper-bot/assets/25500827/f8d87b0e-3cd9-46de-ae26-19b8ea43481a)

**Comment by CVB91** [comment]
I believe this is the part of the script which analyses *your own wallet* for token accounts. If you send some USDC to your wallet then the token account should be created automatically and then this part of the script should work

**Comment by napzter13** [comment]
![image](https://github.com/fdundjer/solana-sniper-bot/assets/25500827/bc78d74d-6d13-4cf2-b293-50009a8bab4f)

Still same error. The wallet has both SOL and USDC 🤔

**Comment by EnterSandman95** [comment]
Hello,
where can I find "RPC endpoint"?

**Comment by CVB91** [comment]
> ![image](https://private-user-images.githubusercontent.com/25500827/299057833-bc78d74d-6d13-4cf2-b293-50009a8bab4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDIzMzUsIm5iZiI6MTcwNjA0MjAzNSwicGF0aCI6Ii8yNTUwMDgyNy8yOTkwNTc4MzMtYmM3OGQ3NGQtNmQxMy00Y2YyLWIyOTMtNTAwMDlhOGJhYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIwMzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNjY1MjkwYjU5ZmMzMmRmMTFjNzdmZDM0MGI4MzlkNWVmOWFkOTVhZmNkYWYwNjA4YmE1Y2UxN2E2MzcxYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pdFOvCJoXsT1XUcywRIvNJXkd012KbqSloeBq_EJX1s)
> 
> Still same error. The wallet has both SOL and USDC 🤔

Try wrapping some SOL. That worked for me. You can do it on Jupiter

**Comment by CVB91** [comment]
> Hello, where can I find "RPC endpoint"?

Here is some detailed information. https://docs.solana.com/cluster/rpc-endpoints

I would say however, going with the public RPC can be annoying, as they rate limit you. Try Helius or Quicknode for private solutions. Helius has a generous free tier.

**Comment by chiochocolate** [comment]
@CVB91 hey great question, do you have discord or something else? I want to ask you some questions about this. Thank you!!
