### ISSUE TITLE
Having problem with private Key, Im using Solflare

### ISSUE THREAD

**Issue by johnben1986** [fdundjer/solana-sniper-bot#25]
I got error with private key

throw new Error('Non-base' + BASE + ' character')

I think Im using different private key format, please advice

**Comment by vin0x** [comment]
Solflare uses an array of numbers in **uint8** format as a private key.
The code expects a key in **base58** format (the most logical, in my opinion). 

1.  You can either go to Notepad++ and convert the array. Or
2.  Export the private key from a Phantom wallet, you will get the key in **base58** format, which is more practical.

**Comment by johnben1986** [comment]
Thanks, I solve it using bs58.encode code
