### ISSUE TITLE
I got error while running the code

### ISSUE THREAD

**Issue by johnben1986** [fdundjer/solana-sniper-bot#27]
throw new SolanaJSONRPCError(
            ^
SolanaJSONRPCError: failed to get accounts owned by program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8: the method getProgramAccounts does not exist/is not available
    at Connection.getProgramAccounts (/Users/solana-sniper-bot-master 2/node_modules/@solana/web3.js/src/connection.ts:3677:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: -32601,
  data: undefined
}

**Comment by fdundjer** [comment]
@johnben1986 Try running the latest version of code

**Comment by johnben1986** [comment]
Same error, I use quicknode

**Comment by fdundjer** [comment]
@johnben1986 That's strange since code doesn't use: getProgramAccounts
Have you tried other RPCs?

**Comment by johnben1986** [comment]
Yeah, I tried and it works fine, consider to close this issues
