### ISSUE TITLE
ERROR: Failed to process pool

### ISSUE THREAD

**Issue by Tyronicax** [fdundjer/solana-sniper-bot#29]
Dear Author,

Thanks for sharing your program. I have tried it but get the below error

[18:13:01.017] INFO: Listening for raydium changes: 0
[18:13:01.017] INFO: Listening for open book changes: 1
[18:16:14.863] ERROR: Failed to process pool
    status: "06"
    nonce: "fe"
    maxOrder: "07"
    depth: "03"
    baseDecimal: "06"
    quoteDecimal: "09"
    state: "01"
    resetFlag: "00"
    minSize: "3b9aca00"
    volMaxCutRatio: "01f4"
    amountWaveRatio: "4c4b40"
    baseLotSize: "0f4240"
    quoteLotSize: "2710"
    minPriceMultiplier: "01"
    maxPriceMultiplier: "3b9aca00"
    systemDecimalValue: "3b9aca00"
    minSeparateNumerator: "05"
    minSeparateDenominator: "2710"
    tradeFeeNumerator: "19"
    tradeFeeDenominator: "2710"
    pnlNumerator: "0c"
    pnlDenominator: "64"
    swapFeeNumerator: "19"
    swapFeeDenominator: "2710"
    baseNeedTakePnl: "00"
    quoteNeedTakePnl: "00"
    quoteTotalPnl: "00"
    baseTotalPnl: "00"
    poolOpenTime: "65c3bad0"
    punishPcAmount: "00"
    punishCoinAmount: "00"
    orderbookToInitTime: "00"
    swapBaseInAmount: "00"
    swapQuoteOutAmount: "00"
    swapBase2QuoteFee: "4e354a"
    swapQuoteInAmount: "7a3343a0"
    swapBaseOutAmount: "d0126e44656f"
    swapQuote2BaseFee: "00"
    baseVault: "DsTV4d2hRksBkaVCixZXoy1oDddquU5EqNvXpX6v21ny"
    quoteVault: "DUzCVWAanSSAJ2a7b5cfePrhfAptDJkZJ4gLPEpykn1W"
    baseMint: "9vZBamqVH4RyQFqcAE5mMAf1VZAriZteVxYpXugWK49d"
    quoteMint: "So11111111111111111111111111111111111111112"
    lpMint: "EfSzMbfsCHYyT1ADaWdaeSPTd6TUZkNf2hboJ6YJNzAU"
    openOrders: "61v931f9xu8j8sNMCnbgaJWccvq5L95XuHAXGDWJenKq"
    marketId: "DYF4VN7u63wzj4UFNKTyu342ExTszR4QS3guL1utyhJJ"
    marketProgramId: "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"
    targetOrders: "7ArUTyFeRr56L2cpmZoAuRYspiMGEpNb5G15bHG3Z3h7"
    withdrawQueue: "11111111111111111111111111111111"
    lpVault: "11111111111111111111111111111111"
    owner: "GThUX1Atko4tqhN2NaiTazWSeFWMuiUvfFnyJyUghFMJ"
    lpReserve: "021d0cad8dac"
    padding: [
      "00",
      "00",
      "00"
    ]
    error: {
      "type": "SendTransactionError",
      "message": "failed to send transaction: Transaction simulation failed: Error processing Instruction 2: custom program error: 0x1",
      "stack":
          Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 2: custom program error: 0x1
              at Connection.sendEncodedTransaction (C:\Users\Stefan\Desktop\Bots\Sol Snip bot\node_modules\@solana\web3.js\src\connection.ts:5920:13)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Connection.sendRawTransaction (C:\Users\Stefan\Desktop\Bots\Sol Snip bot\node_modules\@solana\web3.js\src\connection.ts:5879:20)
      "logs": [
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program ComputeBudget111111111111111111111111111111 invoke [1]",
        "Program ComputeBudget111111111111111111111111111111 success",
        "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]",
        "Program log: CreateIdempotent",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
        "Program log: Instruction: GetAccountDataSize",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1569 of 392795 compute units",
        "Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Transfer: insufficient lamports 904720, need 2039280",
        "Program 11111111111111111111111111111111 failed: custom program error: 0x1",
        "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 11473 of 399700 compute units",
        "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL failed: custom program error: 0x1"
      ]
    }

**Comment by fdundjer** [comment]
Hey @Tyronicax, looks like you don't have enough sol on your wallet.

**Comment by Tyronicax** [comment]
@fdundjer, oh yes that fixed it! I dont understand why SOL & WSOL are needed though. Why not only SOL?

Very nice script btw! As already mentioned a sell option is needed since i cannot click fast enough to sell with a profit :)

**Comment by fdundjer** [comment]
@Tyronicax for swapping tokens you need wsol. You can read more here: https://station.jup.ag/guides/general/wrapped-sol#why-the-need-to-wrap-sol

**Comment by arya09021998** [comment]
@Tyronicax if you are looking for a sell script contact me...!

**Comment by Tyronicax** [comment]
@arya09021998 , are you able to add your sell script to this project? Would help @fdundjer :)
