### ISSUE TITLE
Sniper bot

### ISSUE THREAD

**Issue by chiochocolate** [fdundjer/solana-sniper-bot#3]
Hey Filip great work!

Ive tried using it, but what wallet do you prefer to use?
And also, do you have any other platform to write you a message? Like gmail or instagram, telegr.

Thank you,

**Comment by fdundjer** [comment]
Hey, thanks! 
I prefer SolFlare. For running the script it doesn't matter which wallet is it. You just need to put your wallet private key in wallet.json file before running the script.

ps. you can drop me a message on discord: ovidije

**Comment by fdundjer** [comment]
I'm closing this issue. Feel free to reopen it if needed.
