### ISSUE TITLE
Error: No SOL token account found in wallet

### ISSUE THREAD

**Issue by paungabriel1** [fdundjer/solana-sniper-bot#30]
![image](https://github.com/fdundjer/solana-sniper-bot/assets/91350962/2f1b4fa9-6b28-43f5-b161-1a0c16a417d4)
How to swap SOL to wSOL?

**Comment by paungabriel1** [comment]
Swaps isn't working, SOL to USDC or raydium and nothing

**Comment by arya09021998** [comment]
for swaping SOL to WSOL 
visit - https://jup.ag/swap/SOL-USDC

![image](https://github.com/fdundjer/solana-sniper-bot/assets/76100875/7dd4bd68-f313-4b64-a444-5a8faf86ad58)
click on this setting ICON 

![image](https://github.com/fdundjer/solana-sniper-bot/assets/76100875/4f0a96dc-26de-4b79-9ee0-b11b32bcb361)
Enable this Radio button

![image](https://github.com/fdundjer/solana-sniper-bot/assets/76100875/9760b237-bac1-44a2-afa7-d469002ea293)
this kind of interface you will see and click on Manage

![image](https://github.com/fdundjer/solana-sniper-bot/assets/76100875/78056e75-b94d-41d9-9337-96ef1d352890)
Here you go you can Swap SOL to WSOL and WSOL to SOL


and also if you are looking for the script to Sell the coin once after bought contact me...

**Comment by mikesens** [comment]
@arya09021998 hello
Could you be so kind as to create PR or share sell method? Another contributor has shared a sell-swap script here, but I believe it could be optimized. Thank you

**Comment by CHToken** [comment]
do you have the script to sell the coin after purchase? @arya09021998
