### ISSUE TITLE
To improve the speed of purchase, what can be done?

### ISSUE THREAD

**Issue by meme-token-lab** [fdundjer/solana-sniper-bot#34]
Hello!
I use "snipe list" and can buy after only 15-17 seconds
my place after purchase is always 90+

tried different settings:
setComputeUnitLimit { units: 1_400_000 } // min 200k max 1.4kk
setComputeUnitPrice { microLamports: 10_000_000 } // 0,01 Sol = Lamport 10000000

Tell me what parameters can be changed or how can the script be improved to get into that 1-5-10 range when purchasing?

Maybe someone has a simple script for the BUY function for a token that has not yet appeared in the pool, so that he tries to buy it and maybe it will be faster (with the error ignored)?

**Comment by fdundjer** [comment]
@meme-token-lab Change processing level to confirmed/processed and get private RPC.
