### ISSUE TITLE
Error: No SOL token account found in wallet: 

### ISSUE THREAD

**Issue by robert1223derty** [fdundjer/solana-sniper-bot#39]
D:\video\sol\solana\buy.ts:28
import { retrieveEnvVariable } from './utils';
                                                         ^        
Error: No SOL token account found in wallet: 9ShLJ6KyegT4X6YXGnqc3bBpGpDwNuYXBqkoKXBMzZm6
    at D:\video\sol\solana\buy.ts:146:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\video\sol\solana\buy.ts:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by robert1223derty** [comment]
thank you

**Comment by leebiblia** [comment]
I was also trying to get WSOL but I can't find a way to swap sol to wsol on phantom

**Comment by fdundjer** [comment]
Marking resolved @robert1223derty
