### ISSUE TITLE
Buys but does not sell

### ISSUE THREAD

**Issue by Petttter** [fdundjer/solana-sniper-bot#40]
Displays an error, but buys and does not sell.
![Zrzut ekranu 2024-02-26 192348](https://github.com/fdundjer/solana-sniper-bot/assets/161325064/0bb4f041-5b28-4458-8bdc-bc74d4276c85)
AUTO_SELL true
SELL_DELAY 3000

what am i doing wrong? ;)

**Comment by Petttter** [comment]
> To nie twoja wina, że funkcja „sprzedaj” jest zepsuta. Spróbuj użyć createAssociatedTokenAccountIdempotentInstruction zamiast createCloseAccountInstruction.

How to do it sir?

**Comment by SwatX18** [comment]
> > To nie twoja wina, że funkcja „sprzedaj” jest zepsuta. Spróbuj użyć createAssociatedTokenAccountIdempotentInstruction zamiast createCloseAccountInstruction.
> 
> How to do it sir?

https://github.com/fdundjer/solana-sniper-bot/issues/22#issuecomment-1924554619

**Comment by robert1223derty** [comment]
Same question, I don't know how to do

**Comment by SwatX18** [comment]
> Same question, I don't know how to do

I gave you the solution, I can't help you more.
You need to understand programming to do this.

**Comment by Commando2024** [comment]
> It's not your fault the "sell" function is broken. Try to use createAssociatedTokenAccountIdempotentInstruction instead createCloseAccountInstruction.

This did not fix the issue, any other advice?

**Comment by fdundjer** [comment]
@Commando2024 @Petttter I'll push the fix for this.
