### ISSUE TITLE
   console.log(poolOpenTime > runTimestamp) is always false.

### ISSUE THREAD

**Issue by realrufans** [fdundjer/solana-sniper-bot#43]
Script doesn't buy at my end because poolOpentime is always less than runtimestamp 

   console.log(poolOpenTime > runTimestamp);

**Comment by realrufans** [comment]
![image](https://github.com/fdundjer/solana-sniper-bot/assets/33923021/f6971ae3-78ca-468a-9d79-f3c61c31973d)

**Comment by arcofs** [comment]
Did you ever figure this out? I'm having the same issue, waited for over 6 hours and nothing. I have another hacky script that monitors new raydium pools and picks up pools every 5 minutes or so
