### ISSUE TITLE
How to convert SOL to WSOL? 

### ISSUE THREAD

**Issue by nasko94** [fdundjer/solana-sniper-bot#49]
Hey, I can't seem to figure out how to convert SOL to WSOL. My Phantom wallet doesn't have this option nor I can exchange sol to wsol. How do you guys do it?

**Comment by BajdeQ** [comment]
go to jup.ag

![1](https://github.com/fdundjer/solana-sniper-bot/assets/108154666/6163c185-fc20-4e2c-9ffc-53b11f682bdc)
![2](https://github.com/fdundjer/solana-sniper-bot/assets/108154666/483cfdd9-2c03-4335-a507-913b5c956df1)
![3](https://github.com/fdundjer/solana-sniper-bot/assets/108154666/cdd6f3cb-7506-4f80-8d8d-95c9397cbce6)
![4](https://github.com/fdundjer/solana-sniper-bot/assets/108154666/a5ed70aa-e920-47ed-a438-d349efef0530)
![5](https://github.com/fdundjer/solana-sniper-bot/assets/108154666/114abc43-8b9b-445e-842e-dcba7dae7031)
![6](https://github.com/fdundjer/solana-sniper-bot/assets/108154666/160e8fcc-9909-4898-af63-972a75634ed9)

**Comment by nasko94** [comment]
@BajdeQ Thank you man! Been looking for this soo long!
