### ISSUE TITLE
Script runs but it's not making any buys o showing errors.

### ISSUE THREAD

**Issue by amazzuca** [fdundjer/solana-sniper-bot#52]
I have USD & SOL in my Wallet. 
I've configured correctly the RPC because I can see requests on my dashboard. 
But when I run the scripts I get the following screenshot but no error thrown or message.
![image](https://github.com/fdundjer/solana-sniper-bot/assets/10656932/a367a0cb-be7e-4f01-8f7a-f1f368450a0e)

What I'm doing wrong or is missconfigured?
Thanks.

**Comment by fdundjer** [comment]
@amazzuca Which RPC are you using?

**Comment by amazzuca** [comment]
Sorry, my bad. I was expecting more buys, but it took a while to make the first purchase. It's working Ok. BTW my RPC is HELIUS. It's ok? or should I change it?

**Comment by khalilshamdan** [comment]
How long di it take.... cause I have been trying for so long, and I haven't succeeded yet

**Comment by khalilshamdan** [comment]
> No, there are very few operations daily, maybe 1 or 2, with USDC. Some months ago were like 4 o 5 daily. Specially at night. (Western hemisphere).

can you please help me with some issues?

1. what RCP do you use?
2. Do you run the code locally or use a virtual machine like Render, Heroku, or Google Cloud?

**Comment by amazzuca** [comment]
Hi. I've tried several RPCs such as shyft, quicknode, etc. just google.

I run the bot on a VPS (Hetzner)



________________________________
De: Khaleel Sami Hamdan ***@***.***>
Enviado: jueves, 5 de diciembre de 2024 04:41
Para: warp-id/solana-trading-bot ***@***.***>
Cc: Alejandro ***@***.***>; State change ***@***.***>
Asunto: Re: [warp-id/solana-trading-bot] Script runs but it's not making any buys o showing errors. (Issue #52)


No, there are very few operations daily, maybe 1 or 2, with USDC. Some months ago were like 4 o 5 daily. Specially at night. (Western hemisphere).

can you please help me with some issues?

  1.  what RCP do you use?
  2.  Do you run the code locally or use a virtual machine like Render, Heroku, or Google Cloud?
