### ISSUE TITLE
Scam becareful

### ISSUE THREAD

**Issue by sainhurera** [fdundjer/solana-sniper-bot#54]
Don't use this code he is stealing your privatekeys

**Comment by a04512** [comment]
sir, it is open-source

**Comment by Estereg** [comment]
HAHAHAHA LMAOOOOOOOOOOOO

**Comment by vicbravo-zz** [comment]
Open source does not always mean secure. If you suspect the code could steal your private key, you should paste the code out there.

**Comment by Thansen1980** [comment]
Please specify in the code, where you see that the private key is send anywhere ?? :)
