### ISSUE TITLE
swapping out after swapping in

### ISSUE THREAD

**Issue by dtmrc** [fdundjer/solana-sniper-bot#7]
i got this to work after a few small changes. 

question, i am trying to figure out the swap transaction to sell at a higher price from the initial buy swap. 

A)  have you figured out where the price data is of the token is stored?  is the value calculated from helper methods in the raydium sdk `Liquidity.computePrice()` methods?  or is it on-chain with an oracle feed elsewhere?
B)  in constructing the swap instruction to sell the tokens at market rate, should i use the same fixed in swap?  or is it fixed out?

**Comment by fdundjer** [comment]
@dtmrc If you are buying for a fixed price, you can use fixed out where minOutValue would be higher than your in price.
Other option I tried is to use: Liqudity.computeAmountOut which gives you market rate price.
