### ISSUE TITLE
[Question] where do we specify the token we want to snipe?

### ISSUE THREAD

**Issue by david-dacruz** [fdundjer/solana-sniper-bot#8]
Hi mate have a quick question where do we specify the token we want to snipe?
Thanks ahead

**Comment by fdundjer** [comment]
Hey @david-dacruz, this script snipes all tokens with liquidity pools created on raydium.
If you want to snipe specific token, you would need to know some details upfront, eg. who is the author of the token.
Script doesn't support that at the moment.

**Comment by david-dacruz** [comment]
Thank you @fdundjer
